# Generated by Django 2.2.15 on 2020-08-27 11:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bbapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='名無し', max_length=255, verbose_name='名前')),
                ('text', models.TextField(verbose_name='コメント')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='投稿日/時間')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bbapp.PostModel', verbose_name='対象記事')),
            ],
            options={
                'db_table': 'comment',
            },
        ),
    ]
